[package]
name = "tracing-core"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt = { version = "1" }

[target.'cfg(target_arch = "xtensa")'.dependencies]
esp-hal = "1"
[target.'cfg(target_arch = "riscv32")'.dependencies]
esp-hal = "1"
