name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  # 1. Check Build & Tests of CLI for Linux, Windows, Mac
  test-cli:
    name: Test CLI (Linux/Windows/Mac)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable
      - name: Build CLI
        run: cargo build --package rustmeter --verbose
      - name: Test CLI
        run: cargo test --package rustmeter --verbose

  # 2. Code-Quality (Formatting + Clippy)
  clippy-fmt:
    name: Clippy & Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Formatting
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  # 3. Build-Check for Embedded (Beacon)
  # Here we only check if it compiles
  build-embedded:
    name: Build Embedded Beacon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Nightly 
        uses: dtolnay/rust-toolchain@nightly
        with:
            #   ESP32-C3 (RISC-V), ESP32-S2 (Xtensa) and STM32 (ARM Cortex-M)
          targets: riscv32imc-unknown-none-elf, xtensa-esp32-none-elf, thumbv7em-none-eabi        
      - name: Build Beacon (RISC-V)
        run: cargo build --package rustmeter-beacon --target riscv32imc-unknown-none-elf --no-default-features
      - name: Build Beacon (Xtensa)
        run: cargo build --package rustmeter-beacon --target xtensa-esp32-none-elf --no-default-features
      - name: Build Beacon (Cortex-M)
        run: cargo build --package rustmeter-beacon --target thumbv7em-none-eabi --no-default-features
